name: go_router_modular
description: "Modular Routing and Dependency Injection for Flutter with GoRouter. Features event-driven architecture for seamless module communication and micro-frontend support."
version: 5.0.0
homepage: https://noble-radiator-9bf.notion.site/749c9f720f004ce2a9a5c64723d208c1?v=e4e46890a8e94b5ca97a050d12f952ca&p=e379fa8efcb045eebf651203839f0b95&pm=s
repository: https://github.com/eduardohr-muniz/go_router_modular
issue_tracker: https://github.com/eduardohr-muniz/go_router_modular/issues

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  event_bus: ^2.0.1
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.0.0
  go_transitions: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
